### PR TITLE
Update to latest dependencies

### PR DESCRIPTION
**Pull request by sectore**

### CODE REVIEW

**Comment by chrisdotcode** [comment]
Hey, thanks a lot!

**Comment by sectore** [comment]
@chrisdotcode Thanks for merging! Any chance to bump `purescript-http-types` to `v0.6.2` (incl. publishing to bower)? I do need these ^ changes to publish another library called [`purescript-isomorphic-fetch`](https://github.com/sectore/purescript-isomorphic-fetch).

**Comment by chrisdotcode** [comment]
@sectore: Sorry about the delay, I was a bit busy prior. I'll merge it in today or tomorrow (and version update + bower push)!

**Comment by chrisdotcode** [comment]
(I'll also need to update the included doc)

**Pull request merged**
